title: Nashra Tazmeen
logo: https://avatars.githubusercontent.com/u/108357611?v=4
description: Data science: turning raw data into actionable insights
#show_downloads: true
theme: jekyll-theme-minimal

